# Hotel amenity select

In [31]:
import pandas as pd
import os
import math

In [32]:
df = pd.read_csv("room_amenities_processed.csv")
df

,Unnamed: 0,room_type_id,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,...,jacuzzi-bathtub,smoking-allowed,electric-blanket,free-welcome-drink,low-floor,complimentary-tea,coffee-tea-maker,hot-spring-access,bedroom_count,confirmation-instant
0,0,1,1,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,dieu hoa ca nhan
1,1,2,0,1,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,0,cua so
2,2,3,0,1,0,0,0,0,0,0,...,NaN,True,NaN,NaN,True,NaN,NaN,NaN,0,hanh lang ngoai
3,3,4,0,1,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,dieu hoa ca nhan
4,4,5,1,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,cua so
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11932,11932,12043,0,0,1,0,0,0,0,0,...,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
11933,11933,12044,0,0,1,0,0,0,0,0,...,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
11934,11934,12045,0,0,0,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
11935,11935,12046,1,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,am nuoc dien
11936,11936,12047,1,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,am nuoc dien

In [33]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11937 entries, 0 to 11936
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   room_type_id                  11937 non-null  int64
 1   large_double_bed              11937 non-null  int64
 2   large_bed                     11937 non-null  int64
 3   single_bed                    11937 non-null  int64
 4   sofa_bed                      11937 non-null  int64
 5   double_bed                    11937 non-null  int64
 6   small_double_bed              11937 non-null  int64
 7   king_size_bed                 11937 non-null  int64
 8   futon_mattress                11937 non-null  int64
 9   bunk_bed                      11937 non-null  int64
 10  flexibility_score             11937 non-null  int64
 11  sqm                           10802 non-null  float64
 12  bathroom_count                11937 non-null  int64
 13  is_private_bathroom           11937 non-null  int64
 14  views                         7928 non-null   object
 15  balcony-terrace               4346 non-null   object
 16  non-smoking-room              3686 non-null   object
 17  closet                        4144 non-null   object
 18  air_conditioning              5540 non-null   object
 19  mini_bar                      2613 non-null   object
 20  hair_dryer                    4382 non-null   object
 21  complimentary-bottled-water   2452 non-null   object
 22  bathtub                       1816 non-null   object
 23  shower                        2727 non-null   object
 24  separate-shower-and-tub       858 non-null    object
 25  refrigerator                  2653 non-null   object
 26  high-floor                    651 non-null    object
 27  dressing-room                 563 non-null    object
 28  ground-floor                  572 non-null    object
 29  private-pool                  615 non-null    object
 30  executive-lounge-access       373 non-null    object
 31  top-floor                     261 non-null    object
 32  complimentary-instant-coffee  912 non-null    object
 33  jacuzzi-bathtub               234 non-null    object
 34  smoking-allowed               386 non-null    object
 35  electric-blanket              268 non-null    object
 36  free-welcome-drink            213 non-null    object
 37  low-floor                     162 non-null    object
 38  complimentary-tea             205 non-null    object
 39  coffee-tea-maker              173 non-null    object
 40  hot-spring-access             40 non-null     object
 41  bedroom_count                 11937 non-null  int64
 42  confirmation-instant          7856 non-null   object
dtypes: float64(1), int64(14), object(28)
memory usage: 3.9+ MB

**Note**: some of the column are objects because they are in the boolean form, we will convert them into 0/1 form

In [35]:
obj_cols = df.select_dtypes(include="object").columns

obj_cols = obj_cols.drop(["confirmation-instant", "views"], errors="ignore")

for col in obj_cols:
    df[col] = df[col].notna().astype(int)

In [36]:
df

,room_type_id,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,...,jacuzzi-bathtub,smoking-allowed,electric-blanket,free-welcome-drink,low-floor,complimentary-tea,coffee-tea-maker,hot-spring-access,bedroom_count,confirmation-instant
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,dieu hoa ca nhan
1,2,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,cua so
2,3,0,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,hanh lang ngoai
3,4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,dieu hoa ca nhan
4,5,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,cua so
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11932,12043,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,NaN
11933,12044,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,NaN
11934,12045,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
11935,12046,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,am nuoc dien
11936,12047,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,am nuoc dien

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11937 entries, 0 to 11936
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   room_type_id                  11937 non-null  int64
 1   large_double_bed              11937 non-null  int64
 2   large_bed                     11937 non-null  int64
 3   single_bed                    11937 non-null  int64
 4   sofa_bed                      11937 non-null  int64
 5   double_bed                    11937 non-null  int64
 6   small_double_bed              11937 non-null  int64
 7   king_size_bed                 11937 non-null  int64
 8   futon_mattress                11937 non-null  int64
 9   bunk_bed                      11937 non-null  int64
 10  flexibility_score             11937 non-null  int64
 11  sqm                           10802 non-null  float64
 12  bathroom_count                11937 non-null  int64
 13  is_private_bathroom           11937 non-null  int64
 14  views                         7928 non-null   object
 15  balcony-terrace               11937 non-null  int32
 16  non-smoking-room              11937 non-null  int32
 17  closet                        11937 non-null  int32
 18  air_conditioning              11937 non-null  int32
 19  mini_bar                      11937 non-null  int32
 20  hair_dryer                    11937 non-null  int32
 21  complimentary-bottled-water   11937 non-null  int32
 22  bathtub                       11937 non-null  int32
 23  shower                        11937 non-null  int32
 24  separate-shower-and-tub       11937 non-null  int32
 25  refrigerator                  11937 non-null  int32
 26  high-floor                    11937 non-null  int32
 27  dressing-room                 11937 non-null  int32
 28  ground-floor                  11937 non-null  int32
 29  private-pool                  11937 non-null  int32
 30  executive-lounge-access       11937 non-null  int32
 31  top-floor                     11937 non-null  int32
 32  complimentary-instant-coffee  11937 non-null  int32
 33  jacuzzi-bathtub               11937 non-null  int32
 34  smoking-allowed               11937 non-null  int32
 35  electric-blanket              11937 non-null  int32
 36  free-welcome-drink            11937 non-null  int32
 37  low-floor                     11937 non-null  int32
 38  complimentary-tea             11937 non-null  int32
 39  coffee-tea-maker              11937 non-null  int32
 40  hot-spring-access             11937 non-null  int32
 41  bedroom_count                 11937 non-null  int64
 42  confirmation-instant          7856 non-null   object
dtypes: float64(1), int32(26), int64(14), object(2)
memory usage: 2.7+ MB

**Note**: There are still many columns that sound the same and ambigious column like confirmation-instant, we will check them and merge or drop them

## Checking the confirmation_instant

In [38]:
df["confirmation-instant"].value_counts()

confirmation-instant
am nuoc dien                                2167
do dung cho giac ngu thoai mai              1923
cua so                                      1703
am nuoc                                      364
hanh lang ngoai                              325
dieu hoa ca nhan                             288
cua so co the mo ra                          285
ruou                                         210
trai cay/do an vat                           200
loi vao bai bien rieng                       126
phong xong kho                               112
do go ngoai troi                             109
phong tam dung                                20
quyen su dung spa mien phi                    11
suoi                                           7
quat                                           5
may ca phe espresso co vien nen (co phi)       1
Name: count, dtype: int64

**Note:** We can see that there is a value = dieu hoa ca nhan which mean they belong to the air_conditioning column, we will map them

In [39]:
mask = df["confirmation-instant"].fillna("").str.contains("dieu hoa ca nhan", case=False)

In [40]:
df.loc[mask, "air_conditioning"] = 1

**Note:** We will drop the confirmation instant since they are filled by the owner and it personal, we dont really need it, we have a lot more amenity we can use

In [41]:
df.drop(columns=["confirmation-instant"], inplace=True)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11937 entries, 0 to 11936
Data columns (total 42 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   room_type_id                  11937 non-null  int64
 1   large_double_bed              11937 non-null  int64
 2   large_bed                     11937 non-null  int64
 3   single_bed                    11937 non-null  int64
 4   sofa_bed                      11937 non-null  int64
 5   double_bed                    11937 non-null  int64
 6   small_double_bed              11937 non-null  int64
 7   king_size_bed                 11937 non-null  int64
 8   futon_mattress                11937 non-null  int64
 9   bunk_bed                      11937 non-null  int64
 10  flexibility_score             11937 non-null  int64
 11  sqm                           10802 non-null  float64
 12  bathroom_count                11937 non-null  int64
 13  is_private_bathroom           11937 non-null  int64
 14  views                         7928 non-null   object
 15  balcony-terrace               11937 non-null  int32
 16  non-smoking-room              11937 non-null  int32
 17  closet                        11937 non-null  int32
 18  air_conditioning              11937 non-null  int32
 19  mini_bar                      11937 non-null  int32
 20  hair_dryer                    11937 non-null  int32
 21  complimentary-bottled-water   11937 non-null  int32
 22  bathtub                       11937 non-null  int32
 23  shower                        11937 non-null  int32
 24  separate-shower-and-tub       11937 non-null  int32
 25  refrigerator                  11937 non-null  int32
 26  high-floor                    11937 non-null  int32
 27  dressing-room                 11937 non-null  int32
 28  ground-floor                  11937 non-null  int32
 29  private-pool                  11937 non-null  int32
 30  executive-lounge-access       11937 non-null  int32
 31  top-floor                     11937 non-null  int32
 32  complimentary-instant-coffee  11937 non-null  int32
 33  jacuzzi-bathtub               11937 non-null  int32
 34  smoking-allowed               11937 non-null  int32
 35  electric-blanket              11937 non-null  int32
 36  free-welcome-drink            11937 non-null  int32
 37  low-floor                     11937 non-null  int32
 38  complimentary-tea             11937 non-null  int32
 39  coffee-tea-maker              11937 non-null  int32
 40  hot-spring-access             11937 non-null  int32
 41  bedroom_count                 11937 non-null  int64
dtypes: float64(1), int32(26), int64(14), object(1)
memory usage: 2.6+ MB

**Note:** we will classify them for better understanding, we will choose some amenity that common and suit for the customer sense for renting the room
- Bed:  
  - `large_double_bed`  
  - `double_bed`  
  - `small_double_bed`  
  - `large_bed`  
  - `king_size_bed`  
  - `single_bed`  
  - `sofa_bed`  
  - `futon_mattress`  
  - `bunk_bed`    
  - `bedroom_count`  
  - `flexibility_score`

- Area: 
  - `sqm`  

- Bathroom / Bath facilities: 
  - `bathroom_count`  
  - `is_private_bathroom`  
  - `bathtub`  
  - `shower`  
  - `separate-shower-and-tub`  
  - `jacuzzi-bathtub`  
  - `hot-spring-access`  

- Comfort / Climate:  
  - `air_conditioning`  
  - `electric-blanket`  

- Personal item / Storage:  
  - `hair_dryer`  
  - `closet`  
  - `dressing-room`  

- Drinks / Food-related amenities:  
  - `mini_bar`  
  - `refrigerator`  
  - `coffee-tea-maker`  
  - `complimentary-bottled-water`  
  - `complimentary-instant-coffee`  
  - `complimentary-tea`  
  - `free-welcome-drink`  

- Policy / Smoking: 
  - `non-smoking-room`  
  - `smoking-allowed`  

- View / Outdoor / Floor:  
  - `views`  
  - `balcony-terrace`  
  - `ground-floor`  
  - `low-floor`  
  - `high-floor`  
  - `top-floor`  

- Premium access / Luxury:  
  - `executive-lounge-access`  
  - `private-pool`  

- Identifier:  
  - `room_type_id`

- We don't have to check the Bed, they are already processed, about the Identifier, we will keep it as the merging part.

We will process the bathroom group a little bit
- jacuzzi-bathtub is a bathtub so we will map them to the bathtub column
- separate-shower-and-tub will be mapped to the shower and bathtub column

In [43]:
# Nếu có jacuzzi-bathtub thì chắc chắn có bathtub
df.loc[df["jacuzzi-bathtub"] == 1, "bathtub"] = 1

# Nếu có separate-shower-and-tub thì có cả bathtub và shower
df.loc[df["separate-shower-and-tub"] == 1, ["bathtub", "shower"]] = 1

In [44]:
df['is_private_bathroom'].value_counts()

is_private_bathroom
1    10987
0      950
Name: count, dtype: int64

In [45]:
df['hot-spring-access'].value_counts()

hot-spring-access
0    11897
1       40
Name: count, dtype: int64

The `hot-spring-access` is not common, so we will drop it. Also, we will drop `separate-shower-and-tub`, `jacuzzi-bathtub`, `hot-spring-access` since we merge it to bathtub and shower

In [46]:
df.drop(columns=["separate-shower-and-tub", "jacuzzi-bathtub"], inplace=True)

Next, we will check the Comfort / Climate group

In [47]:
cols = ["electric-blanket", "air_conditioning"]

for col in cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- electric-blanket ---
electric-blanket
0    11669
1      268
Name: count, dtype: int64

--- air_conditioning ---
air_conditioning
0    6109
1    5828
Name: count, dtype: int64

Next, we will check the Personal item / Storage group

In [48]:
cols = ["hair_dryer", "closet", "dressing-room"]

for col in cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- hair_dryer ---
hair_dryer
0    7555
1    4382
Name: count, dtype: int64

--- closet ---
closet
0    7793
1    4144
Name: count, dtype: int64

--- dressing-room ---
dressing-room
0    11374
1      563
Name: count, dtype: int64

Next we will check the Drinks / Food-related amenities group
- We have to know that mini bar means "tu lanh mini" so it belongs to the refrigerator column, we will map it and drop column mini_bar

In [49]:
# Nếu có mini_bar thì set refrigerator = 1
df.loc[df["mini_bar"] == 1, "refrigerator"] = 1

# Drop mini_bar
df.drop(columns=["mini_bar"], inplace=True)

In [50]:
cols = [
    "refrigerator",
    "coffee-tea-maker",
    "complimentary-bottled-water",
    "complimentary-instant-coffee",
    "complimentary-tea",
    "free-welcome-drink"
]

for col in cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- refrigerator ---
refrigerator
0    6805
1    5132
Name: count, dtype: int64

--- coffee-tea-maker ---
coffee-tea-maker
0    11764
1      173
Name: count, dtype: int64

--- complimentary-bottled-water ---
complimentary-bottled-water
0    9485
1    2452
Name: count, dtype: int64

--- complimentary-instant-coffee ---
complimentary-instant-coffee
0    11025
1      912
Name: count, dtype: int64

--- complimentary-tea ---
complimentary-tea
0    11732
1      205
Name: count, dtype: int64

--- free-welcome-drink ---
free-welcome-drink
0    11724
1      213
Name: count, dtype: int64

We will check the Policy / Smoking group

In [51]:
mask = (df["non-smoking-room"] == 0) & (df["smoking-allowed"] == 0)
mask.sum()

7865

We can see that there a a lot of rows that do not contain the information about smoking allowed or not, therefore, we will kindly drop those 2 columns to prevent the ambigious

In [52]:
df.drop(columns=["non-smoking-room", "smoking-allowed"], inplace=True)

We will check View / Outdoor / Floor group:

In [53]:
df['views'].value_counts()

views
thanh pho                        2235
ngoai troi                       1592
vuon                             1195
nui                               809
song                              369
duong pho                         313
bien                              282
ho                                187
khong co cua so                   184
be boi                            156
san trong                         132
bien (huong mot phan)             102
thien nhien                        92
dai duong                          87
bai bien                           58
cong vien                          46
dai duong (mot phan)               21
nong thon                          17
duoc vao phong cho thuong gia      13
ho (mot phan)                      12
thang canh                          5
cang                                4
vinh                                4
canh dem                            4
thung lung                          3
tang thuong                         3
dam pha                             2
ben du thuyen                       1
Name: count, dtype: int64

We can see there are many types of view are simmilar to each other, we will group them into 6 groups (sea, lake, pool, city, garden, nature, no view:

In [54]:
import pandas as pd

SEA_VALUES = {
    "song", "bien", "bien (huong mot phan)", "dai duong", "bai bien",
    "dai duong (mot phan)", "cang", "vinh", "dam pha", "ben du thuyen"
}

LAKE_VALUES = {"ho", "ho (mot phan)"}

POOL_VALUES = {"be boi"}

CITY_VALUES = {"thanh pho", "duong pho", "cong vien"}

GARDEN_VALUES = {"vuon", "san trong"}

NATURE_VALUES = {
    "ngoai troi", "nui", "thien nhien", "nong thon",
    "thang canh", "canh dem", "thung lung"
}

def map_view(v):
    if pd.isna(v):
        return "no view"
    
    v = str(v).strip().lower()
    
    if v in SEA_VALUES:
        return "sea"
    if v in LAKE_VALUES:
        return "lake"
    if v in POOL_VALUES:
        return "pool"
    if v in CITY_VALUES:
        return "city"
    if v in GARDEN_VALUES:
        return "garden"
    if v in NATURE_VALUES:
        return "nature"
    
    return "no view"

In [55]:
df["views"] = df["views"].apply(map_view)

# check distribution
df["views"].value_counts(dropna=False)

views
no view    4209
city       2594
nature     2522
garden     1327
sea         930
lake        199
pool        156
Name: count, dtype: int64

In [56]:
cols = ["balcony-terrace", "ground-floor", "low-floor", "high-floor", "top-floor"]

for col in cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- balcony-terrace ---
balcony-terrace
0    7591
1    4346
Name: count, dtype: int64

--- ground-floor ---
ground-floor
0    11365
1      572
Name: count, dtype: int64

--- low-floor ---
low-floor
0    11775
1      162
Name: count, dtype: int64

--- high-floor ---
high-floor
0    11286
1      651
Name: count, dtype: int64

--- top-floor ---
top-floor
0    11676
1      261
Name: count, dtype: int64

Finally, we will check the Premium access / Luxury group

In [57]:
cols = ["executive-lounge-access", "private-pool"]

for c in cols:
    print(f"\n--- {c} ---")
    print(df[c].value_counts(dropna=False))

--- executive-lounge-access ---
executive-lounge-access
0    11564
1      373
Name: count, dtype: int64

--- private-pool ---
private-pool
0    11322
1      615
Name: count, dtype: int64

Some of the `executive-lounge-access` we mapped wrong since the data is not clean, we will drop it

In [58]:
df.drop(columns=["executive-lounge-access"], inplace=True)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11937 entries, 0 to 11936
Data columns (total 36 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   room_type_id                  11937 non-null  int64
 1   large_double_bed              11937 non-null  int64
 2   large_bed                     11937 non-null  int64
 3   single_bed                    11937 non-null  int64
 4   sofa_bed                      11937 non-null  int64
 5   double_bed                    11937 non-null  int64
 6   small_double_bed              11937 non-null  int64
 7   king_size_bed                 11937 non-null  int64
 8   futon_mattress                11937 non-null  int64
 9   bunk_bed                      11937 non-null  int64
 10  flexibility_score             11937 non-null  int64
 11  sqm                           10802 non-null  float64
 12  bathroom_count                11937 non-null  int64
 13  is_private_bathroom           11937 non-null  int64
 14  views                         11937 non-null  object
 15  balcony-terrace               11937 non-null  int32
 16  closet                        11937 non-null  int32
 17  air_conditioning              11937 non-null  int32
 18  hair_dryer                    11937 non-null  int32
 19  complimentary-bottled-water   11937 non-null  int32
 20  bathtub                       11937 non-null  int32
 21  shower                        11937 non-null  int32
 22  refrigerator                  11937 non-null  int32
 23  high-floor                    11937 non-null  int32
 24  dressing-room                 11937 non-null  int32
 25  ground-floor                  11937 non-null  int32
 26  private-pool                  11937 non-null  int32
 27  top-floor                     11937 non-null  int32
 28  complimentary-instant-coffee  11937 non-null  int32
 29  electric-blanket              11937 non-null  int32
 30  free-welcome-drink            11937 non-null  int32
 31  low-floor                     11937 non-null  int32
 32  complimentary-tea             11937 non-null  int32
 33  coffee-tea-maker              11937 non-null  int32
 34  hot-spring-access             11937 non-null  int32
 35  bedroom_count                 11937 non-null  int64
dtypes: float64(1), int32(20), int64(14), object(1)
memory usage: 2.4+ MB

In [60]:
df.to_csv(
    "room_amenities_select.csv",
    index=False,
    encoding="utf-8-sig"   # để mở bằng Excel không lỗi dấu
)